import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { createRouter, RouterProvider, createMemoryHistory } from '@tanstack/react-router'
// Generated by @tanstack/router-plugin on dev/build. Gitignored.
import { routeTree } from './routeTree.gen'
import { ErrorBoundary } from './shell/ErrorBoundary'
// Forwards Vite build/parse errors into the crash surface (W3). Import for side effect.
import './lib/vite-error-recovery'
import './styles/index.css'

// Memory history: this is a desktop shell, not a browser. The shell persists its
// last location to localStorage itself (see __root) so it restores on launch.
const router = createRouter({ routeTree, history: createMemoryHistory() })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

// Let main route the app before an agent snapshot (see electron/main/snapshot.ts).
// Memory history isn't URL-driven, so navigation has to go through the router.
window.hearth?.view?.onNavigate(({ path }) => {
  router.history.push(path)
})

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <ErrorBoundary>
      <RouterProvider router={router} />
    </ErrorBoundary>
  </StrictMode>,
)
