import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { createRouter, RouterProvider, createMemoryHistory } from '@tanstack/react-router'
// Generated by @tanstack/router-plugin on dev/build. Gitignored.
import { routeTree } from './routeTree.gen'
import './styles/index.css'

// Memory history: this is a desktop shell, not a browser. The shell persists its
// last location to localStorage itself (see __root) so it restores on launch.
const router = createRouter({ routeTree, history: createMemoryHistory() })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
)
